version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "infra"
      - "github_actions"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      python-deps:
        patterns:
          - "*"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/apps/dashboard"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      dashboard-deps:
        patterns:
          - "*"
